### ISSUE TITLE
Website CSS

### ISSUE THREAD

**Issue by MirayXS** [berichan/GetNHSE#1]
# Website CSS

## If you want, i can send a pull request to have CSS (CSS from <a href="https://mirayxs.github.io/ACNH-IMAGEZIP/assets/css/index.css">ACNH-IMAGEZIP</a>)
> CSS on-action: <a href="https://mirayxs.github.io/ACNH-IMAGEZIP">ACNH-IMAGEZIP</a>

**Comment by berichan** [comment]
Sure! If you have a good idea for how the website should look then feel free to create a pull request (:

**Comment by MirayXS** [comment]
Ok! i'll see what i can do :D
