### ISSUE TITLE
Propose: 404.html file-page

### ISSUE THREAD

**Issue by MirayXS** [berichan/GetNHSE#3]
# Propose: 404.html file-page

## The default GitHub Pages 404 looks like this:

![image](https://user-images.githubusercontent.com/55494819/87203885-dd19df80-c303-11ea-9f3b-6a6a2da72b21.png)

## it will use my default 404 css
> (example: https://mirayxs.github.io/MirayCDN/404.html)
### [But if you want, i can try to have a different css !]

**Comment by berichan** [comment]
Yours is fine! Could you have it also link to index.html?

**Comment by MirayXS** [comment]
sure! that's what i was thinking :D i was thinking of another lil text that said "back to main page" and redirects to index.html

**Comment by berichan** [comment]
Sounds great! One thing I noticed is that the text is a little cut off for me, both at the top and bottom of the web page on mobile.

<img src ="https://user-images.githubusercontent.com/66521620/87204868-e86a0c80-c2fd-11ea-9c49-72067f9c4aaf.png" width="300">
<img src="https://user-images.githubusercontent.com/66521620/87204871-ea33d000-c2fd-11ea-8c50-61ffd103e492.png" width="300">

Can that be resized correctly too?

**Comment by MirayXS** [comment]
i'll try to see later :)

**Comment by MirayXS** [comment]
so found out removing the

```
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```

would quickly-fix the issue. 

I just want to know if you are okay with that being removed..

![image](https://user-images.githubusercontent.com/55494819/87207954-831e1780-c30d-11ea-9f33-1b1b773713fe.png)

**Comment by berichan** [comment]
The font having lines through it is a little jarring (is it being repeated?) still perfectly legible though!

**Comment by MirayXS** [comment]
ohh don't mind that xD it may be the quality of that photo because i firstrly sent that on discord (and if u know discord sometimes make images shit)

**Comment by MirayXS** [comment]
I can confirm though that the font is the same from a computer view, i can **try** to send a zoomed-in fonts image

**Comment by MirayXS** [comment]
![image](https://user-images.githubusercontent.com/55494819/87209113-1278fa00-c311-11ea-970c-bd8d542dc79e.png)
