### ISSUE TITLE
Add troubleshooting message on API fail

### ISSUE THREAD

**Issue by dylanhilton** [berichan/GetNHSE#5]
This is a great resource, but the call to Azure DevOps is blocked by [Privacy Badger](https://privacybadger.org/), a popular extension by @EFForg. Perhaps after a timeout period, a message could prompt the user to disable Privacy Badger/other ad blockers.

<img width="375" alt="image" src="https://user-images.githubusercontent.com/25556826/88116661-b9199200-cb7e-11ea-8ace-40099def36dd.png">

**Comment by berichan** [comment]
I'm also using Privacy Badger and have never come across this issue. Are you using a custom configuration? Could you show me how the site currently looks like for you?

**Comment by dylanhilton** [comment]
Sure. Do you have DNT enabled? Here's the output of the Privacy Badger diagnostics described [here](https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain):

```
**** ACTION_MAP for azure.com
azure.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 0
}
dev.azure.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1595591263696
}
**** SNITCH_MAP for azure.com
azure.com [
  "docker.com",
  "github.com",
  "google.com"
]
```

<img width="715" alt="image" src="https://user-images.githubusercontent.com/25556826/88126269-d195a680-cb96-11ea-9b90-7657b9f8becd.png">

**Comment by berichan** [comment]
I had to manually put the domains for azure in my list to get it to happen, they weren't in there by default even after a reinstall, so I assume they were removed at some point? 

I could add a catch-all scriptblocker message, but I think at this time the "Something wrong above?" message does suffice. I'll leave this open for a while if anyone wants to PR with a good solution.

**Comment by berichan** [comment]
Had some time to check this out. Let me know how the site behaves for you now :)

**Comment by dylanhilton** [comment]
Looks great, thank you!
