### ISSUE TITLE
Size Difference after playing the DLC

### ISSUE THREAD

**Issue by AzrouStone** [berichan/GetNHSE#7]
I began hacking in money and completed the first half of the game with KK Slider, no issue and was just a few days ago. Then I did a lot of homes in the paradise planning but I didn't complete it when I noticed I have all food recipes yet I can't read this new one I got so I was going to edit a flag to say that I can (mistake on my part) but now I can't even open up my main at all.

**Comment by berichan** [comment]
Please submit a report on the NHSE repo if you believe an issue was caused by NHSE, this repo is just an Azure pipeline resolver
