### ISSUE TITLE
Edited villagers refuse to talk and speak with their default catchphrases 

### ISSUE THREAD

**Issue by PizzaWithCheese1** [berichan/GetNHSE#8]
I used NHSE to change my villagers into different characters, but seem to run in two different issues!
1. The villager, despite having a different appearance after being edited, still uses their default catchphrase from their previous character.
2. After the greeting line, the villager refuses to talk, leaving an empty speech bubble.

**Comment by berichan** [comment]
GetNHSE is just an azure pipeline link builder, create an error report on the NHSE repo if you have an issue with the program itself
