### ISSUE TITLE
Storage items double

### ISSUE THREAD

**Issue by Ronshere** [berichan/GetNHSE#9]
hi
Every once in a while the items in storage double.  It will go from 1 to 2 to 4 to 8 of each item and so on.  

![doubling](https://github.com/berichan/GetNHSE/assets/25470922/38bc3288-40ea-47b7-92e4-1c23cda87502)

**Comment by berichan** [comment]
GetNHSE is just an azure pipeline link builder, create an error report on the NHSE repo if you have an issue with the program itself
